"""M2.8 task created_at column

Revision ID: 762bc15388e8
Revises: c2ff4bd6d11d
Create Date: 2026-09-30 06:00:33.497672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762bc15388e8'
down_revision: Union[str, None] = 'c2ff4bd6d11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows for this NOT NULL column; the ORM's
    # default=... only covers new inserts, not rows that already exist at migration time.
    op.add_column('task', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,
                                     server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'created_at')
    # ### end Alembic commands ###
