"""M2.2 initial schema

Revision ID: 85ca6b7d547a
Revises: 
Create Date: 2026-09-29 16:29:02.466300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ca6b7d547a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('auth_ref', sa.String(), nullable=True),
    sa.Column('card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mode',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turn_policy', sa.String(), nullable=True),
    sa.Column('stop_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('output_type', sa.String(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('egress_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mode_id'], ['mode.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_turn_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('from', sa.String(), nullable=False),
    sa.Column('to', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('in_reply_to', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('requires_ack', sa.Boolean(), nullable=False),
    sa.Column('refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_format', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("visibility in ('all', 'recipients', 'moderator')", name='ck_message_visibility'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_message_conversation_seq')
    )
    op.create_table('session_agent',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('seat_order', sa.Integer(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('harness', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('isolation', sa.String(), nullable=False),
    sa.CheckConstraint("isolation in ('shared', 'own')", name='ck_session_agent_isolation'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'agent_id')
    )
    op.create_table('turn',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_turn_session_seq')
    )
    op.create_table('report',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('from', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('output_ref', sa.String(), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.message_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'from')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('turn')
    op.drop_table('session_agent')
    op.drop_table('message')
    op.drop_table('artifact')
    op.drop_table('session')
    op.drop_table('sandbox')
    op.drop_table('task')
    op.drop_table('mode')
    op.drop_table('agent')
    # ### end Alembic commands ###
