"""M2.10 session stop_reason column

Revision ID: 85d8f94a9824
Revises: 762bc15388e8
Create Date: 2026-09-30 11:20:08.713730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d8f94a9824'
down_revision: Union[str, None] = '762bc15388e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('stop_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'stop_reason')
    # ### end Alembic commands ###
