"""add fallback_active to session

Revision ID: 8dffe6e372ab
Revises: b97861c351c0
Create Date: 2026-10-03 00:46:04.695032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dffe6e372ab'
down_revision: Union[str, None] = 'b97861c351c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('fallback_active', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'fallback_active')
    # ### end Alembic commands ###
