"""M3.2 session_agent removed_at column

Revision ID: b97861c351c0
Revises: f73079274d8f
Create Date: 2026-09-30 17:12:44.372636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97861c351c0'
down_revision: Union[str, None] = 'f73079274d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_agent', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_agent', 'removed_at')
    # ### end Alembic commands ###
