"""M2.7 rolling summary columns on session

Revision ID: c2ff4bd6d11d
Revises: 85ca6b7d547a
Create Date: 2026-09-29 20:13:08.350126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ff4bd6d11d'
down_revision: Union[str, None] = '85ca6b7d547a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('rolling_summary', sa.Text(), nullable=True))
    op.add_column('session', sa.Column('rolling_summary_through_seq', sa.Integer(), nullable=True))
    # server_default backfills existing rows for this NOT NULL column; the ORM's
    # default=0 only covers new inserts, not rows that already exist at migration time.
    op.add_column('session', sa.Column('stale_argument_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'stale_argument_count')
    op.drop_column('session', 'rolling_summary_through_seq')
    op.drop_column('session', 'rolling_summary')
    # ### end Alembic commands ###
