"""M2.11 unique constraints on agent.name and mode.name

Revision ID: f73079274d8f
Revises: 85d8f94a9824
Create Date: 2026-09-30 12:09:05.677264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73079274d8f'
down_revision: Union[str, None] = '85d8f94a9824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_agent_name', 'agent', ['name'])
    op.create_unique_constraint('uq_mode_name', 'mode', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mode_name', 'mode', type_='unique')
    op.drop_constraint('uq_agent_name', 'agent', type_='unique')
    # ### end Alembic commands ###
